/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as LaporRouteImport } from './routes/lapor'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AnggaranRouteImport } from './routes/anggaran'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LaporanIndexRouteImport } from './routes/laporan.index'
import { Route as LaporanIdRouteImport } from './routes/laporan.$id'

const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LaporRoute = LaporRouteImport.update({
  id: '/lapor',
  path: '/lapor',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AnggaranRoute = AnggaranRouteImport.update({
  id: '/anggaran',
  path: '/anggaran',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LaporanIndexRoute = LaporanIndexRouteImport.update({
  id: '/laporan/',
  path: '/laporan/',
  getParentRoute: () => rootRouteImport,
} as any)
const LaporanIdRoute = LaporanIdRouteImport.update({
  id: '/laporan/$id',
  path: '/laporan/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/anggaran': typeof AnggaranRoute
  '/auth': typeof AuthRoute
  '/lapor': typeof LaporRoute
  '/leaderboard': typeof LeaderboardRoute
  '/profil': typeof ProfilRoute
  '/laporan/$id': typeof LaporanIdRoute
  '/laporan/': typeof LaporanIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/anggaran': typeof AnggaranRoute
  '/auth': typeof AuthRoute
  '/lapor': typeof LaporRoute
  '/leaderboard': typeof LeaderboardRoute
  '/profil': typeof ProfilRoute
  '/laporan/$id': typeof LaporanIdRoute
  '/laporan': typeof LaporanIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/anggaran': typeof AnggaranRoute
  '/auth': typeof AuthRoute
  '/lapor': typeof LaporRoute
  '/leaderboard': typeof LeaderboardRoute
  '/profil': typeof ProfilRoute
  '/laporan/$id': typeof LaporanIdRoute
  '/laporan/': typeof LaporanIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/anggaran'
    | '/auth'
    | '/lapor'
    | '/leaderboard'
    | '/profil'
    | '/laporan/$id'
    | '/laporan/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/anggaran'
    | '/auth'
    | '/lapor'
    | '/leaderboard'
    | '/profil'
    | '/laporan/$id'
    | '/laporan'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/anggaran'
    | '/auth'
    | '/lapor'
    | '/leaderboard'
    | '/profil'
    | '/laporan/$id'
    | '/laporan/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AnggaranRoute: typeof AnggaranRoute
  AuthRoute: typeof AuthRoute
  LaporRoute: typeof LaporRoute
  LeaderboardRoute: typeof LeaderboardRoute
  ProfilRoute: typeof ProfilRoute
  LaporanIdRoute: typeof LaporanIdRoute
  LaporanIndexRoute: typeof LaporanIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lapor': {
      id: '/lapor'
      path: '/lapor'
      fullPath: '/lapor'
      preLoaderRoute: typeof LaporRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anggaran': {
      id: '/anggaran'
      path: '/anggaran'
      fullPath: '/anggaran'
      preLoaderRoute: typeof AnggaranRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laporan/': {
      id: '/laporan/'
      path: '/laporan'
      fullPath: '/laporan/'
      preLoaderRoute: typeof LaporanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laporan/$id': {
      id: '/laporan/$id'
      path: '/laporan/$id'
      fullPath: '/laporan/$id'
      preLoaderRoute: typeof LaporanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AnggaranRoute: AnggaranRoute,
  AuthRoute: AuthRoute,
  LaporRoute: LaporRoute,
  LeaderboardRoute: LeaderboardRoute,
  ProfilRoute: ProfilRoute,
  LaporanIdRoute: LaporanIdRoute,
  LaporanIndexRoute: LaporanIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
